export type Sector = {
  id: string;
  nameEn: string;
  nameAr: string;
  icon: string;
  descriptionEn: string;
  descriptionAr: string;
  services: string[];
  whyUsEn: string;
  whyUsAr: string;
  projectExamples: { titleEn: string; titleAr: string }[];
};

export const sectorsData: Sector[] = [
  {
    id: "real-estate",
    nameEn: "Real Estate & Construction",
    nameAr: "العقارات والبناء",
    icon: "🏗️",
    descriptionEn: "Professional project management for residential and commercial developments, infrastructure projects, and construction planning.",
    descriptionAr: "إدارة مشاريع احترافية للتطوير السكني والتجاري، مشاريع البنية التحتية، وتخطيط البناء.",
    services: ["project-planning", "vendor-management", "business-coordination", "operational-support"],
    whyUsEn: "We bring extensive UAE real estate experience, coordinating developers, contractors, and regulatory bodies to deliver on time and on budget.",
    whyUsAr: "نمتلك خبرة واسعة في قطاع العقارات الإماراتي، وننسق بين المطورين والمقاولين والجهات التنظيمية لتسليم المشاريع في الوقت المحدد وضمن الميزانية.",
    projectExamples: [
      { titleEn: "Dubai Creek Tower Infrastructure", titleAr: "برج خور دبي للبنية التحتية" },
      { titleEn: "Residential Complex in JVC", titleAr: "مجمع سكني في جميرا فيليج سيركل" },
    ],
  },
  {
    id: "renting",
    nameEn: "Renting & Leasing",
    nameAr: "التأجير والاستئجار",
    icon: "🚗",
    descriptionEn: "Project management for real estate leasing, property management, vehicle fleet rental, and bus charter services.",
    descriptionAr: "إدارة المشاريع للتأجير العقاري، إدارة الممتلكات، تأجير أساطيل المركبات، وخدمات تأجير الحافلات.",
    services: ["vendor-management", "operational-support", "administrative-services"],
    whyUsEn: "We optimize asset utilization and lease administration for landlords, fleet operators, and transport companies.",
    whyUsAr: "نعمل على تحسين استغلال الأصول وإدارة عقود الإيجار لأصحاب العقارات ومشغلي الأساطيل وشركات النقل.",
    projectExamples: [
      { titleEn: "Fleet Management for Dubai Taxi", titleAr: "إدارة أسطول لتاكسي دبي" },
      { titleEn: "Property Leasing Platform Integration", titleAr: "دمج منصة تأجير عقاري" },
    ],
  },
  {
    id: "bus-services",
    nameEn: "Bus Services & Transport",
    nameAr: "خدمات الحافلات والنقل",
    icon: "🚌",
    descriptionEn: "Project management for passenger bus transport, tourist bus services, staff & school bus fleet management, and international bus routes.",
    descriptionAr: "إدارة مشاريع لنقل الركاب بالحافلات، خدمات الحافلات السياحية، إدارة أساطيل حافلات الموظفين والمدارس، وخطوط الحافلات الدولية.",
    services: ["operational-support", "vendor-management", "business-coordination"],
    whyUsEn: "We help transport operators improve efficiency, safety, and compliance with RTA regulations through strategic project management.",
    whyUsAr: "نساعد مشغلي النقل على تحسين الكفاءة والسلامة والامتثال للوائح هيئة الطرق والمواصلات من خلال إدارة المشاريع الاستراتيجية.",
    projectExamples: [
      { titleEn: "UAE National Bus Fleet Optimization", titleAr: "تحسين أسطول الحافلات الوطنية في الإمارات" },
      { titleEn: "School Bus Routing & Safety System", titleAr: "نظام مسار وسلامة الحافلات المدرسية" },
    ],
  },
  {
    id: "it",
    nameEn: "IT & Technology",
    nameAr: "تكنولوجيا المعلومات",
    icon: "💻",
    descriptionEn: "Project management for software development, digital transformation, IT infrastructure rollouts, and smart city technology projects.",
    descriptionAr: "إدارة مشاريع تطوير البرمجيات، التحول الرقمي، تنفيذ البنية التحتية لتقنية المعلومات، ومشاريع تكنولوجيا المدن الذكية.",
    services: ["project-planning", "business-coordination", "consultancy-services"],
    whyUsEn: "We bridge the gap between business goals and technical execution, ensuring IT projects deliver measurable value.",
    whyUsAr: "نسد الفجوة بين الأهداف التجارية والتنفيذ التقني، لضمان أن مشاريع تقنية المعلومات تحقق قيمة ملموسة.",
    projectExamples: [
      { titleEn: "Smart City Command Center", titleAr: "مركز قيادة المدينة الذكية" },
      { titleEn: "ERP Implementation for Government Entity", titleAr: "تنفيذ نظام تخطيط موارد المؤسسات لهيئة حكومية" },
    ],
  },
  {
    id: "events",
    nameEn: "Events & Entertainment",
    nameAr: "الفعاليات والترفيه",
    icon: "🎪",
    descriptionEn: "Project management for corporate events, conferences, exhibitions, festivals, and trade shows.",
    descriptionAr: "إدارة مشاريع الفعاليات المؤسسية، المؤتمرات، المعارض، المهرجانات، والمعارض التجارية.",
    services: ["business-coordination", "operational-support", "administrative-services"],
    whyUsEn: "We coordinate logistics, vendors, and stakeholders to ensure seamless event execution, from planning to post-event analysis.",
    whyUsAr: "نقوم بتنسيق الخدمات اللوجستية والموردين وأصحاب المصلحة لضمان تنفيذ فعاليات سلسة، من التخطيط إلى تحليل ما بعد الفعالية.",
    projectExamples: [
      { titleEn: "Dubai Expo 2020 Pavilion Coordination", titleAr: "تنسيق جناح إكسبو 2020 دبي" },
      { titleEn: "Annual Tech Conference Management", titleAr: "إدارة المؤتمر التقني السنوي" },
    ],
  },
  {
    id: "healthcare",
    nameEn: "Healthcare",
    nameAr: "الرعاية الصحية",
    icon: "🏥",
    descriptionEn: "Project management for hospital and clinic construction, healthcare facility expansion, and medical equipment installation coordination.",
    descriptionAr: "إدارة مشاريع بناء المستشفيات والعيادات، توسعة المرافق الصحية، وتنسيق تركيب المعدات الطبية.",
    services: ["project-planning", "vendor-management", "operational-support"],
    whyUsEn: "We navigate complex healthcare regulations to deliver facilities that meet international standards of care.",
    whyUsAr: "نحن نجتاز اللوائح الصحية المعقدة لتسليم مرافق تلبي المعايير الدولية للرعاية.",
    projectExamples: [
      { titleEn: "Private Hospital Expansion in Dubai", titleAr: "توسعة مستشفى خاص في دبي" },
      { titleEn: "Medical Equipment Rollout for SEHA", titleAr: "طرح المعدات الطبية لصحة" },
    ],
  },
  {
    id: "energy",
    nameEn: "Energy & Utilities",
    nameAr: "الطاقة والمرافق",
    icon: "⚡",
    descriptionEn: "Project management for oil & gas projects, renewable energy initiatives, and utility infrastructure.",
    descriptionAr: "إدارة مشاريع النفط والغاز، مبادرات الطاقة المتجددة، والبنية التحتية للمرافق.",
    services: ["project-planning", "consultancy-services", "vendor-management"],
    whyUsEn: "We manage complex energy projects with a focus on safety, sustainability, and regulatory compliance.",
    whyUsAr: "ندير مشاريع الطاقة المعقدة مع التركيز على السلامة والاستدامة والامتثال التنظيمي.",
    projectExamples: [
      { titleEn: "100MW Solar Farm Project Management", titleAr: "إدارة مشروع مزرعة شمسية بقدرة 100 ميجاوات" },
      { titleEn: "Natural Gas Pipeline Coordination", titleAr: "تنسيق خط أنابيب الغاز الطبيعي" },
    ],
  },
  {
    id: "government",
    nameEn: "Government & Public Sector",
    nameAr: "الحكومة والقطاع العام",
    icon: "🏛️",
    descriptionEn: "Project management for urban planning, public infrastructure development, and government agency programs.",
    descriptionAr: "إدارة المشاريع للتخطيط الحضري، تطوير البنية التحتية العامة، وبرامج الوكالات الحكومية.",
    services: ["project-planning", "business-coordination", "consultancy-services"],
    whyUsEn: "We understand the unique procurement and reporting requirements of UAE government entities.",
    whyUsAr: "نحن نفهم متطلبات المشتريات وإعداد التقارير الفريدة للجهات الحكومية الإماراتية.",
    projectExamples: [
      { titleEn: "Dubai Urban Masterplan Support", titleAr: "دعم المخطط الحضري الرئيسي لدبي" },
      { titleEn: "Government Digital Services Transformation", titleAr: "تحول الخدمات الرقمية الحكومية" },
    ],
  },
  {
    id: "retail",
    nameEn: "Retail & Commercial",
    nameAr: "التجزئة والتجارة",
    icon: "🛍️",
    descriptionEn: "Project management for new product development, market testing, and retail chain expansion.",
    descriptionAr: "إدارة المشاريع لتطوير منتجات جديدة، اختبار السوق، وتوسعة سلاسل البيع بالتجزئة.",
    services: ["consultancy-services", "operational-support", "administrative-services"],
    whyUsEn: "We help retailers optimize store openings, supply chain, and customer experience projects.",
    whyUsAr: "نساعد تجار التجزئة على تحسين افتتاح المتاجر وسلسلة التوريد ومشاريع تجربة العملاء.",
    projectExamples: [
      { titleEn: "40-Store Opening Rollout", titleAr: "طرح افتتاح 40 متجراً" },
      { titleEn: "Loyalty Program Implementation", titleAr: "تنفيذ برنامج الولاء" },
    ],
  },
  {
    id: "oil-gas",
    nameEn: "Oil & Gas",
    nameAr: "النفط والغاز",
    icon: "🛢️",
    descriptionEn: "Project management for exploration, extraction, logistics coordination, pipeline and refinery projects.",
    descriptionAr: "إدارة مشاريع الاستكشاف والاستخراج وتنسيق الخدمات اللوجستية ومشاريع خطوط الأنابيب والمصافي.",
    services: ["project-planning", "vendor-management", "consultancy-services"],
    whyUsEn: "We bring rigorous safety and compliance standards to upstream and downstream oil & gas operations.",
    whyUsAr: "نحن نطبق معايير صارمة للسلامة والامتثال في عمليات النفط والغاز في المنبع والمصب.",
    projectExamples: [
      { titleEn: "Offshore Drilling Support", titleAr: "دعم الحفر البحري" },
      { titleEn: "Refinery Maintenance Shutdown", titleAr: "إيقاف تشغيل صيانة المصفاة" },
    ],
  },
  {
    id: "education",
    nameEn: "Education & Training",
    nameAr: "التعليم والتدريب",
    icon: "📚",
    descriptionEn: "Project management for school construction, educational facility management, and government training programs.",
    descriptionAr: "إدارة مشاريع بناء المدارس، إدارة المرافق التعليمية، وبرامج التدريب الحكومية.",
    services: ["project-planning", "operational-support", "administrative-services"],
    whyUsEn: "We help educational institutions modernize facilities and implement effective training programs.",
    whyUsAr: "نساعد المؤسسات التعليمية على تحديث المرافق وتنفيذ برامج تدريب فعالة.",
    projectExamples: [
      { titleEn: "Private School Campus Expansion", titleAr: "توسعة حرم مدرسة خاصة" },
      { titleEn: "Teacher Training Program", titleAr: "برنامج تدريب المعلمين" },
    ],
  },
  {
    id: "facilities",
    nameEn: "Facilities Management (FM)",
    nameAr: "إدارة المرافق",
    icon: "🔧",
    descriptionEn: "Project management for building maintenance, security services coordination, and catering/food services management.",
    descriptionAr: "إدارة مشاريع صيانة المباني، تنسيق خدمات الأمن، وإدارة خدمات التموين والطعام.",
    services: ["operational-support", "vendor-management", "business-coordination"],
    whyUsEn: "We optimize FM operations to reduce costs and improve service delivery across your real estate portfolio.",
    whyUsAr: "نحن نحسن عمليات إدارة المرافق لتقليل التكاليف وتحسين تقديم الخدمات عبر محفظتك العقارية.",
    projectExamples: [
      { titleEn: "Integrated FM for Commercial Tower", titleAr: "إدارة مرافق متكاملة لبرج تجاري" },
      { titleEn: "Security System Upgrade", titleAr: "ترقية نظام الأمن" },
    ],
  },
  {
    id: "hospitality",
    nameEn: "Hospitality & Tourism",
    nameAr: "الضيافة والسياحة",
    icon: "🏨",
    descriptionEn: "Project management for hotel construction, renovation, resort development, and tourist facility management.",
    descriptionAr: "إدارة مشاريع بناء الفنادق وتجديدها، تطوير المنتجعات، وإدارة المرافق السياحية.",
    services: ["project-planning", "operational-support", "consultancy-services"],
    whyUsEn: "We help hoteliers and tourism boards deliver exceptional guest experiences through efficient project delivery.",
    whyUsAr: "نساعد أصحاب الفنادق ومجالس السياحة على تقديم تجارب ضيوف استثنائية من خلال تسليم المشاريع بكفاءة.",
    projectExamples: [
      { titleEn: "5-Star Hotel Renovation", titleAr: "تجديد فندق 5 نجوم" },
      { titleEn: "Tourist Attraction Development", titleAr: "تطوير منطقة جذب سياحي" },
    ],
  },
  {
    id: "renewable",
    nameEn: "Renewable Energy",
    nameAr: "الطاقة المتجددة",
    icon: "☀️",
    descriptionEn: "Project management for solar farm projects, wind energy initiatives, and green building certifications.",
    descriptionAr: "إدارة مشاريع مزارع الطاقة الشمسية، مبادرات طاقة الرياح، وشهادات المباني الخضراء.",
    services: ["project-planning", "consultancy-services", "vendor-management"],
    whyUsEn: "We accelerate the energy transition by managing renewable projects from feasibility to commissioning.",
    whyUsAr: "نحن نسرع عملية تحول الطاقة من خلال إدارة المشاريع المتجددة من الجدوى إلى التشغيل.",
    projectExamples: [
      { titleEn: "Solar Farm Project Management (100MW)", titleAr: "إدارة مشروع مزرعة شمسية (100 ميجاوات)" },
      { titleEn: "LEED Certification Consulting", titleAr: "استشارات شهادة الريادة في الطاقة والتصميم البيئي" },
    ],
  },
];